<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="8" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-21T16:24:20Z" name="Surefire suite" finished-at="2022-12-21T16:24:37Z" duration-ms="16451">
    <groups>
    </groups>
    <test started-at="2022-12-21T16:24:20Z" name="Surefire test" finished-at="2022-12-21T16:24:37Z" duration-ms="16451">
      <class name="secxndary_framework.test.OzByTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:secxndary_framework.test.OzByTest@16267862]" started-at="2022-12-21T16:24:20Z" name="setUp" finished-at="2022-12-21T16:24:22Z" duration-ms="1374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="AddressAdding_ShouldReturnError_WhenAddressIsNonExistent()[pri:0, instance:secxndary_framework.test.OzByTest@16267862]" started-at="2022-12-21T16:24:22Z" name="AddressAdding_ShouldReturnError_WhenAddressIsNonExistent" finished-at="2022-12-21T16:24:29Z" duration-ms="7436" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at secxndary_framework.test.OzByTest.AddressAdding_ShouldReturnError_WhenAddressIsNonExistent(OzByTest.java:171)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddressAdding_ShouldReturnError_WhenAddressIsNonExistent -->
        <test-method is-config="true" signature="stopBrowser()[pri:0, instance:secxndary_framework.test.OzByTest@16267862]" started-at="2022-12-21T16:24:29Z" name="stopBrowser" finished-at="2022-12-21T16:24:29Z" duration-ms="117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopBrowser -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:secxndary_framework.test.OzByTest@16267862]" started-at="2022-12-21T16:24:29Z" name="setUp" finished-at="2022-12-21T16:24:30Z" duration-ms="884" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="EnterNumberOfGoods_ShouldReturnError_WhenNumberOfGoods_IsMoreThan99()[pri:0, instance:secxndary_framework.test.OzByTest@16267862]" started-at="2022-12-21T16:24:30Z" name="EnterNumberOfGoods_ShouldReturnError_WhenNumberOfGoods_IsMoreThan99" finished-at="2022-12-21T16:24:37Z" duration-ms="6335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnterNumberOfGoods_ShouldReturnError_WhenNumberOfGoods_IsMoreThan99 -->
        <test-method is-config="true" signature="stopBrowser()[pri:0, instance:secxndary_framework.test.OzByTest@16267862]" started-at="2022-12-21T16:24:37Z" name="stopBrowser" finished-at="2022-12-21T16:24:37Z" duration-ms="120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopBrowser -->
      </class> <!-- secxndary_framework.test.OzByTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
